In [1]:
import numpy as np

In [2]:
revenue  = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [8]:
print("the profit/loss is : \n",revenue-expenses)

the profit/loss is : 
 [[100 110 120]
 [ 14  20  20]
 [  4   8  10]]


In [6]:
price_per_unit = np.array([1000,400,1200])
unit = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [12]:
print("the revenue generated is : ")
print("   2018 2019 2020")
print(np.multiply(price_per_unit,unit)) #if size of the matrixes are not same then it consider to be same this is called broadcasting

the revenue generated is : 
   2018 2019 2020
[[30000 16000 60000]
 [ 5000  4000 18000]
 [ 2000  2000  8400]]


In [13]:
print("the revenue generated is : ")
print("   2018 2019 2020")
print(np.dot(price_per_unit,unit))

the revenue generated is : 
   2018 2019 2020
[34400 50000 64400]


In [14]:
#excercise convert the following matrix values in dollars to indian rupees
revenue_in_dollars = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])

In [15]:
revenue_in_dollars

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [17]:
print("the converted matrix in indian rupees is : ")
75*revenue_in_dollars

the converted matrix in indian rupees is : 


array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [18]:
units_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit = np.array([20,30,15])

In [19]:
np.dot(price_per_unit,units_sold)

array([1900, 2640, 1430])